// <auto-generated />
using HomeGardenWeb.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeGardenWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241014181253_Improvment")]
    partial class Improvment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeGardenWeb.Models.Category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("category_id"));

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("category_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HomeGardenWeb.Models.Plants", b =>
                {
                    b.Property<int>("plant_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("plant_id"));

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("plant_id");

                    b.HasIndex("category_id");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("HomeGardenWeb.Models.WateringFrequency", b =>
                {
                    b.Property<int>("frequency_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("frequency_id"));

                    b.Property<string>("frequency_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("plant_id")
                        .HasColumnType("int");

                    b.Property<int>("water_volume")
                        .HasColumnType("int");

                    b.Property<int>("watering_interval_days")
                        .HasColumnType("int");

                    b.HasKey("frequency_id");

                    b.HasIndex("plant_id");

                    b.ToTable("WateringFrequency");
                });

            modelBuilder.Entity("HomeGardenWeb.Models.Plants", b =>
                {
                    b.HasOne("HomeGardenWeb.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HomeGardenWeb.Models.WateringFrequency", b =>
                {
                    b.HasOne("HomeGardenWeb.Models.Plants", "Plant")
                        .WithMany("WateringFrequencies")
                        .HasForeignKey("plant_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("HomeGardenWeb.Models.Plants", b =>
                {
                    b.Navigation("WateringFrequencies");
                });
#pragma warning restore 612, 618
        }
    }
}
